import Head from 'next/head'
import Image from 'next/image'

// test

export default function Home() {
  return (
    <div>
      <Head>
        <title>Final Grade Calculator</title>
        <meta name="Calculator for grade needed on certain assignments to pass a class with a given grade." content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      </main>
    </div>
  )
}
